name: Publish Element Types

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      registry:
        description: 'NPM Registry URL'
        required: false
        type: string
        default: 'https://registry.npmjs.org'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Verify package structure
        run: |
          echo "Checking package structure..."
          [ -d "dist" ] || (echo "Error: dist directory missing!" && exit 1)
          [ -f "dist/index.js" ] || (echo "Error: dist/index.js missing!" && exit 1)
          [ -f "dist/index.d.ts" ] || (echo "Error: dist/index.d.ts missing!" && exit 1)
          echo "dist/index.js and dist/index.d.ts found."
          echo "Final package.json:"
          cat package.json

      - name: Publish to npm
        run: pnpm publish --access=public --no-git-checks 
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_REGISTRY: ${{ github.event.inputs.registry || 'https://registry.npmjs.org' }} 